server:
  port: 8000
  servlet:
    context-path: /hxmall

spring:
  application:
    name: hxmall

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.112.252.226:3333/hxmall?tinyInt1isBit=false&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: status
      logic-not-delete-value: 1
  type-enums-package: com.lslg.hxmall.entity.enums
  configuration:
    map-underscore-to-camel-case: true